version: '3'

services:
  database:
    env_file:
      - .env.prod.local

  app:
    env_file:
      - .env.prod.local
    build:
      target: app_prod

  server:
    env_file:
      - .env.prod.local
    build:
      target: server_prod
