parameters:
services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
#
#  App\Doctrine\:
#    resource: '../src/Doctrine/'
#    tags: ['doctrine.orm.entity_listener']
#
#  App\EventListener\:
#    resource: '../src/EventListener/'
#    tags: ['kernel.event_listener']

#  App\EventListener\ResourceResolvingListener:
#    class: 'App\EventListener\ResourceResolvingListener'
#    tags:
#      - {name: kernel.event_listener, priority: 1}

#  App\EventListener\AuthListener:
#    class: 'App\EventListener\AuthListener'
#    tags:
#      - {
#          name: kernel.event_listener,
#          event: auth.registration_success,
#          method: onRegistrationSuccess
#        }

# App\Renderer\NodeRenderer:
#    class: 'App\Renderer\NodeRenderer'
#    arguments:
#      $requestSocket: 'hello' #'%env(string:REQUEST_SOCKET)%'
#      $responseSocket: 'hello' #'%env(string:RESPONSE_SOCKET)%'
#
